### ISSUE TITLE
Check number of reads in fastp output trim.fastq files

### ISSUE THREAD

**Issue by svarona** [nf-core/viralrecon#292]
### Description of feature

We suggest the introducction of a new checkpoint after fastp trimming simmilar to the one existing after the primer trimming:
https://github.com/nf-core/viralrecon/blob/42e38bba3da80484bc480f53d2130642a349e8c6/workflows/illumina.nf#L218

to test wether the output trim.fastq.gz is empty or not. We could add it after this peace of code:

https://github.com/nf-core/viralrecon/blob/42e38bba3da80484bc480f53d2130642a349e8c6/subworkflows/nf-core/fastqc_fastp.nf#L53

**Comment by poojasgupta** [comment]
I think I am facing a similar issue which might get fixed after addition of the feature request suggested by @svarona. 
Sometimes, when my input fastq files are empty or very small due to failed sequencing or becomes empty after the fastp trimming step, the pipeline fails at the fastqc step. When this happens and I remove the failed sample, the pipeline completes successfully.
Here is the error message that I get. 
```
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:FASTQC_FASTP:FASTQC_TRIM (220110_SDSDN16_UT_A01290_220117)'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:FASTQC_FASTP:FASTQC_TRIM (220110_SDSDN16_UT_A01290_220117)` terminated with an error exit status (1)

Command executed:

  [ ! -f  220110_SDSDN16_UT_A01290_220117.fastq.gz ] && ln -s 220110_SDSDN16_UT_A01290_220117.trim.fastq.gz 220110_SDSDN16_UT_A01290_220117.fastq.gz
  fastqc --quiet --threads 6 220110_SDSDN16_UT_A01290_220117.fastq.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALRECON:ILLUMINA:FASTQC_FASTP:FASTQC_TRIM":
      fastqc: $( fastqc --version | sed -e "s/FastQC v//g" )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Failed to process 220110_SDSDN16_UT_A01290_220117.fastq.gz
  java.io.EOFException
  	at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:269)
  	at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:259)
  	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
  	at java.base/java.util.zip.GZIPInputStream.(GZIPInputStream.java:80)
  	at java.base/java.util.zip.GZIPInputStream.(GZIPInputStream.java:92)
  	at uk.ac.babraham.FastQC.Utilities.MultiMemberGZIPInputStream.(MultiMemberGZIPInputStream.java:37)
  	at uk.ac.babraham.FastQC.Sequence.FastQFile.(FastQFile.java:80)
  	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:106)
  	at uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:159)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.(OfflineRunner.java:121)
  	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
```

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/viralrecon/pull/314/commits/a1f810b2b2eb56a2769979fc04dc656d6de424f6 https://github.com/nf-core/viralrecon/pull/314/commits/6a0bc3151331ab2610caab84a4e76bc258d98eaa
