### ISSUE TITLE
ERROR ~ Error executing process > 'NFCORE_VIRALRECON:NANOPORE:ARTIC_MINION'

### ISSUE THREAD

**Issue by alethomas** [nf-core/viralrecon#383]
### Description of the bug

When running nf-core/viralrecon, the medaka minion throws an error. Seems the model cannot be downloaded via the medaka minion script. scm file with github credentials is present, internet connection is available. 

### Command used and terminal output

```console
nextflow run nf-core/viralrecon -qs 4 -revision 2.6.0 -profile docker 
--input results/benchmarking/nf-core-viralrecon/nanopore/sample-sheets/2_ont/sample_sheet.csv --sequencing_summary data/RAW/ONT_batch2/sequencing_summary.txt 
--fastq_dir resources/benchmarking/data/nf-core-viralrecon/2_ont/fastq_pass 
--fast5_dir resources/benchmarking/data/nf-core-viralrecon/2_ont/fast5_pass 
--platform nanopore 
--genome 'MN908947.3' 
--primer_set_version 3 
--artic_minion_caller medaka 
--artic_minion_medaka_model r941_min_fast_g303 
--outdir results/benchmarking/nf-core-viralrecon/nanopore/medaka/2_ont

Command error:
  [M::mm_idx_stat::0.007*3.40] distinct minimizers: 5587 (99.93% are singletons); average occurrences: 1.004; average spacing: 5.332; total length: 29903
  [M::worker_pipeline::17.215*4.14] mapped 365148 sequences
  [M::main] Version: 2.24-r1122
  [M::main] CMD: minimap2 -a -x map-ont -t 12 ./primer-schemes/nCoV-2019/V3/nCoV-2019.reference.fasta 2_ont.fastq.gz
  [M::main] Real time: 17.218 sec; CPU: 71.326 sec; Peak RSS: 0.489 GB
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/medaka/medaka.py", line 35, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/usr/local/lib/python3.8/site-packages/medaka/models.py", line 66, in resolve_model
      raise DownloadError(
  medaka.models.DownloadError: The model file for r941_min_fast_g303 is not already installed and could not be downloaded. Check you are connected to the internet and try again.
```

### Relevant files

[nextflow.log](https://github.com/nf-core/viralrecon/files/11895814/nextflow.log)

### System information

nextflow version 23.04.1.5866
Linux server
locally executed in docker container
nf-core/viralrecon 2.6.0

**Comment by svarona** [comment]
Sorry for the late reply @alethomas ! We will have a closer look to this to see what happens, but a workaround we do for the CI tests is downloading the model before running the pipeline trough: `wget https://github.com/nanoporetech/medaka/raw/master/medaka/data/r941_min_high_g360_model.hdf5`

This might temporarily solve the problem.
